#pragma once

#include <vector>
#include <glm/vec3.hpp>

#include "physics/CollisionEvent.h"

class Registry;

// Hand-rolled physics. Advances all rigid bodies by one fixed step. 7A does
// gravity + semi-implicit Euler integration; 7B adds collision detection and
// impulse resolution. Stepped from SuGarApp::updateSystems on the fixed 60 Hz
// tick, so it only runs in Play mode.
class PhysicsWorld {
public:
    glm::vec3 gravity{0.0f, -9.81f, 0.0f};

    void step(Registry& registry, float deltaTime);

    // Contacts generated by the most recent step(), valid until the next step().
    // SuGarApp dispatches these to behaviors' onCollision after stepping.
    const std::vector<CollisionEvent>& getCollisionEvents() const { return collisionEvents; }

    // AABB tests the broadphase performed in the most recent step. Diagnostic, in the
    // same spirit as Renderer::submittedDrawCalls(): the grid degenerating into an
    // all-pairs scan is invisible to a correctness test — a degenerate grid answers
    // every query right — so the property has to be measured, not compared
    // (DevDocs/DESIGN_BROADPHASE_SCALE.md).
    size_t lastBroadphaseCandidateCount() const { return broadphaseCandidateCount; }

private:
    std::vector<CollisionEvent> collisionEvents;
    size_t broadphaseCandidateCount = 0;
};
