#pragma once

#include <vector>
#include <glm/vec3.hpp>

#include "physics/CollisionEvent.h"

class Registry;

// Hand-rolled physics. Advances all rigid bodies by one fixed step. 7A does
// gravity + semi-implicit Euler integration; 7B adds collision detection and
// impulse resolution. Stepped from SuGarApp::updateSystems on the fixed 60 Hz
// tick, so it only runs in Play mode.
class PhysicsWorld {
public:
    glm::vec3 gravity{0.0f, -9.81f, 0.0f};

    void step(Registry& registry, float deltaTime);

    // Contacts generated by the most recent step(), valid until the next step().
    // SuGarApp dispatches these to behaviors' onCollision after stepping.
    const std::vector<CollisionEvent>& getCollisionEvents() const { return collisionEvents; }

private:
    std::vector<CollisionEvent> collisionEvents;
};
